// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQnF8qiQMFMp0vmQy_uIC5GPrRIRAN_Go',
    appId: '1:95748954348:web:1dfffd3fe0c74574eeedc9',
    messagingSenderId: '95748954348',
    projectId: 'libraryapp-af87c',
    authDomain: 'libraryapp-af87c.firebaseapp.com',
    storageBucket: 'libraryapp-af87c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBP5Dc7isOzADrz24U3f4Bsld0dWNagT4',
    appId: '1:95748954348:android:7f69ba0f68b8a340eeedc9',
    messagingSenderId: '95748954348',
    projectId: 'libraryapp-af87c',
    storageBucket: 'libraryapp-af87c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1wv56eeT6CqhilvpSFfmd5XjuyWVSQL4',
    appId: '1:95748954348:ios:16dd2ad786b42595eeedc9',
    messagingSenderId: '95748954348',
    projectId: 'libraryapp-af87c',
    storageBucket: 'libraryapp-af87c.appspot.com',
    iosBundleId: 'com.example.libraryAppSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1wv56eeT6CqhilvpSFfmd5XjuyWVSQL4',
    appId: '1:95748954348:ios:16dd2ad786b42595eeedc9',
    messagingSenderId: '95748954348',
    projectId: 'libraryapp-af87c',
    storageBucket: 'libraryapp-af87c.appspot.com',
    iosBundleId: 'com.example.libraryAppSample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQnF8qiQMFMp0vmQy_uIC5GPrRIRAN_Go',
    appId: '1:95748954348:web:ec80c09c47054ae7eeedc9',
    messagingSenderId: '95748954348',
    projectId: 'libraryapp-af87c',
    authDomain: 'libraryapp-af87c.firebaseapp.com',
    storageBucket: 'libraryapp-af87c.appspot.com',
  );
}
